FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y mariadb-server && \
    rm -rf /var/lib/apt/lists/*

COPY ./tools/db.sh /usr/local/bin/db.sh
COPY ./config/50-server.cnf /etc/mysql/mariadb.conf.d/
RUN chmod +x /usr/local/bin/db.sh

EXPOSE 3306

CMD ["db.sh"]