FROM debian:bookworm

RUN apt-get update -y && apt-get install -y mariadb-server

COPY ./tools/db.sh /db.sh
COPY ./config/50-server.cnf /etc/mysql/mariadb.conf.d/

EXPOSE 3306

CMD ["bash", "/db.sh"]
