- name : Install docker
  apt:
      name: docker.io
      state: present # it means install if missing

- name : Install docker-compose
  apt:
      name: docker-compose
      state: present

- name: Check how long copying takes
  command: date

- name: Create deployment directory
  file:
    path: /opt/wordpress
    state: directory
    mode: '0755'

- name: Copy docker-compose and app files (excluding volumes)
  synchronize:
    src: files/
    dest: /opt/wordpress/
    rsync_opts:
      - "--exclude=volumes/"

- name: Run docker-compose up
  command: docker-compose up -d
  args:
        chdir: /opt/wordpress/
        
