# SPDX-License-Identifier: MIT-0
---
# tasks file for setup

- name: Update and Upgrade apt packages
  apt:
    update_cache: true
    upgrade: dist
  ignore_errors: true
  tags: system

- name: Install required system packages
  apt:
    name:
      - docker.io
      - python3-pip
      - curl
    state: present
    update_cache: true
  tags: packages

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags: docker

- name: Remove legacy docker-compose v1 binary if present
  file:
    path: /usr/local/bin/docker-compose
    state: absent
  ignore_errors: true
  tags: docker-compose

- name: Install Docker Compose v2 as CLI plugin
  block:
    - name: Create Docker CLI plugins directory
      file:
        path: "/home/{{ ansible_user }}/.docker/cli-plugins"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Download Docker Compose v2.27.0
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
        dest: "/home/{{ ansible_user }}/.docker/cli-plugins/docker-compose"
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
  tags: docker-compose

- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version
  changed_when: false
  ignore_errors: true
  tags: docker-compose


- name: Create application data directory
  ansible.builtin.file:
    path: /home/application/data
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Create MariaDB volume directory
  ansible.builtin.file:
    path: /home/application/data/mariadb
    state: directory
    mode: '0755'
    owner: "999"  # MariaDB typically runs as UID 999
    group: "999"

- name: Create WordPress volume directory
  ansible.builtin.file:
    path: /home/application/data/wordpress
    state: directory
    mode: '0755'
    owner: "www-data"  # Typically UID 33
    group: "www-data"

- name: Verify directory structure
  ansible.builtin.command: ls -la /home/application/data
  register: dir_listing
  changed_when: false

- name: Display directory structure
  ansible.builtin.debug:
    var: dir_listing.stdout_lines

- name: Ensure phpMyAdmin directory exists
  file:
    path: /etc/phpmyadmin
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: directories

- name: Deploy .env configuration file
  template:
    src: ../templates/data.j2
    dest: /home/application/.env
  tags: config

- name: Deploy application source files
  copy:
    src: files/
    dest: /home/application/
  notify: run docker-compose
  tags: deploy
