FROM debian:bookworm

RUN apt-get update -y --fix-missing
           
RUN apt-get install -y wget php php-fpm  php-mysql mariadb-client

RUN mkdir -p /var/www

RUN cd /var/www/ && wget https://wordpress.org/latest.tar.gz && tar xvf latest.tar.gz
 
RUN cd /var/www && rm -f latest.tar.gz

COPY ./config/www.conf /etc/php/8.2/fpm/pool.d/

COPY ./config/wp /usr/local/bin/

RUN cd /usr/local/bin && chmod +x wp

COPY /tools/sv.sh .

EXPOSE 9000

CMD ["bash", "sv.sh"]