services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - net
    volumes:
      - wp-vol:/var/www/html 
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    networks:
      - net
    env_file:
      - .env   
    volumes:  
      - mariadb-volume:/var/lib/mysql/
    restart: always
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    networks:
      - net
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp-vol:/var/www/html 
    restart: always
    
volumes:
  wp-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/application/data/wordpress
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/application/data/mariadb
      o: bind

networks:
  net:
    name: docker_net
    driver: bridge
