services:    
  db:
    env_file:
      - .env
    build: ./mariadb/.
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - DataBase:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u$$MY_USER", "-p$$MY_PASS"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build: ./wordpress/.
    container_name: wordpress-cont
    restart: unless-stopped
    volumes:
      - Wordpress:/var/www/html  # Removed the extra hyphen
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - IP=${IP}
      - BLOG_TITLE=${BLOG_TITLE}
      - AD_USER=${AD_USER}
      - AD_PASSWORD=${AD_PASS}
      - AD_EMAIL=${AD_EMAIL}
      - SP_USER=${SP_USER}
      - SP_EMAIL=${SP_EMAIL}
      - SP_PASS=${SP_PASS}
    networks:
      - app-network
     
  phpmyadmin:
    depends_on:
      - db
    env_file:
      - .env
    image: phpmyadmin:fpm
    container_name: phpmyadmin-cont
    restart: always
    volumes:
      - phpmyadmin_data:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
      - phpmyadmin
    build: ./nginx/.
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "443:443"
    restart: always
    volumes:
      - Wordpress:/var/www/wordpress
      - phpmyadmin_data:/var/www/html
    networks:
      - app-network

volumes:
  Wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/files
  DataBase:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/db
  phpmyadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/phpmyadmin

networks:  
  app-network:
    name: web-network