services:
  nginx: 
    build: 
      context: "./requirements/nginx"   
    ports:
      - "80:80"
      - "443:443"  
    networks:  
      - inception-net  
    env_file:  
      - .env
    volumes:  
      -  wp_data:/var/www/html
    depends_on:
      - phpwordpress 

  mariadb:  
    build:  
      context: "./requirements/Mariadb"  
    ports:   
      - "3306:3306"    
    volumes:  
      - mariadb_data:/var/lib/mysql
    networks:  
      - inception-net  
    env_file:  
      - .env 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${WP_URL}"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpwordpress:   
    build:   
      context: "./requirements/phpwordpress"  
    ports: 
      - "9000:9000"  
    networks:   
      - inception-net   
    env_file:
      - .env
    volumes:  
      - wp_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: application-phpmyadmin
    ports:
      - "8080:80"
    networks:
      - inception-net
    environment:
      PMA_HOST: mariadb 
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 128M
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${WP_URL}:80"]
      interval: 10s
      timeout: 5s
      retries: 3

networks: 
  inception-net:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind 

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wp_data
      o: bind
