services:    
  db:
    env_file:
      - .env
    build: ./mariadb/
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - /opt/wordpress/volumes/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u$$MY_USER", "-p$$MY_PASS"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build: ./wordpress/
    container_name: wordpress-cont
    image: wordpress:mytag
    restart: always
    volumes:
      - /opt/wordpress/volumes/wordpress:/opt/wordpress
    networks:
      - app-network
    
  phpmyadmin:
    depends_on:
      - db
    env_file:
      - .env
    image: phpmyadmin:fpm
    container_name: phpmyadmin-cont
    restart: always
    volumes:
      - /opt/wordpress/volumes/phpmyadmin:/opt/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
      - phpmyadmin
    build: ./nginx/
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "443:443"
    restart: always
    volumes:
      - /opt/wordpress/volumes/wordpress:/opt/wordpress
      - /opt/wordpress/volumes/phpmyadmin:/opt/html
    networks:
      - app-network

networks:
  app-network:
