services:
  nginx: 
    build: 
      context: "./requirements/nginx"   
    ports:
      - "80:80"
      - "443:443"  
    networks:  
      - inception-net  
    env_file:  
      - .env
    volumes:  
      -  wp_data:/var/www/html
    depends_on:
      - phpwordpress 

  mariadb:  
    build:  
      context: "./requirements/Mariadb"  
    ports:   
      - "3306:3306"    
    volumes:  
      - mariadb_data:/var/lib/mysql
    networks:  
      - inception-net  
    env_file:  
      - .env 

  phpwordpress:   
    build:   
      context: "./requirements/phpwordpress"  
    ports: 
      - "9000:9000"  
    networks:   
      - inception-net   
    env_file:
      - .env
    volumes:  
      - wp_data:/var/www/html
    depends_on:
      - mariadb

networks: 
  inception-net:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind 

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wp_data
      o: bind
